### PR TITLE
Added Heroku Deploy

### PR DESCRIPTION
**Pull request by xtc-dev**

### CODE REVIEW

**Comment by Pillow-Dev** [comment]
Bruh the proxy isn't even complete yet

**Comment by xtc-dev** [comment]
> Bruh the proxy isn't even complete yet

He keeps promoting it as if it is. It's completely broken in terms of deploying to major IDEs/Dynamic App Hosting services such as repl.it or Heroku.

**Comment by deopdeop** [comment]
I am not promoting it as it is done also it fully works on repl.it also don't lie in the descriptoin

**Comment by deopdeop** [comment]
I am not promoting it as it is done also it fully works on repl.it also don't lie in the description, when it is ready I will setup auto ci builds

**Pull request closed without merging**
